### ISSUE TITLE
Split this github repository into banch of anothers

### ISSUE THREAD

**Issue by bubuntoid** [bubuntoid/Ethereal#20]
Минусы того, что у нас будет все в одном репозитории:
* Если делать git clone -> будет захватывать миллион ненужных сурсов (возможно некоторым нужен только фронт/десктоп/сервер)
* CI/CD
* При билде будут скачиваться много вероятно ненужных зависимостей

Для разработки не на web application, где будет использоваться исключительно логика YOVPS.Core проекта - ide вероятно будет билдить все существующие проекты, это как минимум:
* YOVPS.WebAPI,
* YOVPS.Desktop, 
* YOVPS.CLI
* Tests

Плюс ко всему возможно добавиться еще чо нибудь, а у каждого проекта свои зависимости (например для билда YOVPS.Desktop придется electron скачивать) - в общем грязь лютая получается.

Идея такая:
Пускай этот репозиторий будет с идеологией некого независимого ядра, в котором из коробки будет идти ТОЛЬКО WebAPI, а кто хочет - используйте либо этот репозиторий как сабмодуль для доступа к самому ядру (например тот же YOVPS.Desktop), или же просто юзайте его в качестве сервера

Итоги:
bubuntoid/YOVPS - ядро/бек:
* YOVPS.Core
* YOVPS.Core.UnitTests
* YOVPS.WebAPI
* YOVPS.WebAPI.AutoTests

bubuntoid/YOVPS.CLI - command line interface:
todo

webgtx/YOVPS.Desktop (если хочешь):
todo

webgtx/YOVPS.Web (ну или с названием сам там разберешься):
переносим сюда Web UI часть

**Comment by bubuntoid** [comment]
так я +- вижу файловую иерархию этого репозитория в итоге: https://github.com/bubuntoid/YOVPS/tree/issue12

**Comment by bubuntoid** [comment]
возможно где то плохо описал/обьяснил, если чо - feel free to ask any questions

**Comment by webgtx** [comment]
Я предлагаю просто разделить бэк-энд и фронт-енд на релизы, я бы хотел что то добавить в бэк со своей стороны. 

Т.е как я вижу наш проект со стороны юзера

#### (Юзер)
- Ага это реп по утилите которая умеет работать с видео на ютубе, и из него создавать плейлисты.
*Он открывает релизы

  **Release 1.0** (Если что там можно скачивать всё отдельно)
- BackEnd Core
- Web Application 
- Desktop Application 
- CLI version (C#)
- CLI version (node.js)

#### (Юзер)
Вау как удобно, весь проект в одном месте, но в тоже время я **могу выбрать что именно мне нужно**. Слава богу мне не надо ходить по разным репам ради другой другого интерфейса одного проекта.

_Таким образом мы можем работать в одном, находить баги, писать в issue, и контролировать версии в релизах._

**Comment by bubuntoid** [comment]
> **Release 1.0** (Если что там можно скачивать всё отдельно)
> 
> * BackEnd Core
> * Web Application
> * Desktop Application
> * CLI version (C#)
> * CLI version (node.js)


ну с релизами это классно конечно, но это не отменяет того, что во время разработки у девов будет каша с зависимостями.

> Я предлагаю просто разделить бэк-энд и фронт-енд на релизы, я бы хотел что то добавить в бэк со своей стороны.

Так репозиторий открытый - открываешь мр -> ждешь одобрения  (+ у тебя есть права, может хоть сразу пушить в мастер) -> мерджишь


Стоит разделить ответственности между репозиториями, слишком много ответвлений планируется.
