### ISSUE TITLE
Bug with thumbnails

### ISSUE THREAD

**Issue by bubuntoid** [bubuntoid/Ethereal#32]
case https://www.youtube.com/watch?v=IbRkwS_xRt8&t=1s&ab_channel=smileybomb123

![image](https://user-images.githubusercontent.com/51204805/133976872-a3ddc1ba-a6d8-4aed-8289-f44490f04ef7.png)

**Comment by bubuntoid** [comment]
case https://www.youtube.com/watch?v=HQ-OYEI9i6E&ab_channel=DJUrashima

![image](https://user-images.githubusercontent.com/51204805/134161036-d2ae8864-3289-4946-8333-501168bc461c.png)

response
```json
{"errorCode":"not_found","errorMessage":"File not found"}
```

**Comment by EMRD95** [comment]
Fixed with https://github.com/bubuntoid/Ethereal/commit/4f8f86fbee8c1a02a05eba4158f15b5a8afe9b30#diff-a67a266dfded3bc1f2abd901361451064d56167580467b28c7a6ef6db545c749

![image](https://github.com/bubuntoid/Ethereal/assets/114953576/1f7648bc-b340-4a00-8182-b245e677d68d)
